### ISSUE TITLE
InMemoryCursor throws NullpointerException when no events in present 

### ISSUE THREAD

**Issue by matusewicz** [zalando-incubator/fahrschein#11]
```
2016-06-30 17:02:35,325 {INFO} [NakadiEventListener-1] [] [de.zalando.fulfillment.domain.logic.EventReceiverGateway] Listening for [fulfillment-order-service-test.customer-shipment-shipped]...
2016-06-30 17:02:35,325 {INFO} [NakadiEventListener-2] [] [de.zalando.fulfillment.domain.logic.EventReceiverGateway] Listening for [fulfillment-order-service-test.customer-shipment-item-cancelled]...
2016-06-30 17:02:35,537 {INFO} [main] [] [de.zalando.fulfillment.event.EventReceiverGatewayTest] Started EventReceiverGatewayTest in 3.259 seconds (JVM running for 5.265)2016-06-30 17:02:36,138 {DEBUG} [NakadiEventListener-2] [] [de.zalando.fulfillment.domain.logic.EventReceiverGateway] Partition [0] has oldest offset [10] and newest offset [9]
2016-06-30 17:02:36,138 {DEBUG} [NakadiEventListener-1] [] [de.zalando.fulfillment.domain.logic.EventReceiverGateway] Partition [0] has oldest offset [88] and newest offset [88]
2016-06-30 17:02:36,174 {ERROR} [NakadiEventListener-1] [] [de.zalando.fulfillment.domain.logic.EventReceiverGateway] Woops
java.lang.NullPointerException
	at org.zalando.fahrschein.InMemoryCursorManager.getCursors(InMemoryCursorManager.java:30) ~[fahrschein-0.1.0.jar:?]
	at org.zalando.fahrschein.NakadiReader.openStream(NakadiReader.java:71) ~[fahrschein-0.1.0.jar:?]
	at org.zalando.fahrschein.NakadiReader.run(NakadiReader.java:145) ~[fahrschein-0.1.0.jar:?]
	at org.zalando.fahrschein.NakadiClient.listen(NakadiClient.java:96) ~[fahrschein-0.1.0.jar:?]
	at de.zalando.fulfillment.domain.logic.EventReceiverGateway.listenForEvent(EventReceiverGateway.java:82) [main/:?]
	at de.zalando.fulfillment.domain.logic.EventReceiverGateway$$FastClassBySpringCGLIB$$c4d32a7.invoke(<generated>) [main/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) [spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115) [spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

**Comment by jhorstmann** [comment]
Should be fixed by PR #12
