### ISSUE TITLE
Thread Safe ManagedCursorManager

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-incubator/fahrschein#166]
It seems the `ManagedCursorManager` is not thread safe.

```
2017-05-12 10:31:15,084 {INFO} [pool-11-thread-1] [org.zalando.fahrschein.NakadiClient] Created subscription for event [a] with id [1d15216d-283f-48c3-aca5-39c91789263a]
2017-05-12 10:31:15,084 {INFO} [pool-11-thread-2] [org.zalando.fahrschein.NakadiClient] Created subscription for event [b] with id [e7d8a428-25d4-4768-a4d7-05c8dece24a8]
2017-05-12 10:31:15,085 {INFO} [pool-11-thread-3] [org.zalando.fahrschein.NakadiClient] Created subscription for event [c] with id [2f7dcb52-e869-4e84-b974-a754ce965c76]
2017-05-12 10:31:15,088 {INFO} [pool-11-thread-4] [org.zalando.fahrschein.NakadiClient] Created subscription for event [d] with id [d385fa22-72a3-4aca-8750-0a5493430bf0]
...
2017-05-12 10:31:15,124 {INFO} [pool-11-thread-4] [org.zalando.fahrschein.NakadiReader] Starting to listen for events for [d]
2017-05-12 10:31:15,128 {INFO} [pool-11-thread-3] [org.zalando.fahrschein.NakadiReader] Starting to listen for events for [c]
2017-05-12 10:31:15,134 {INFO} [pool-11-thread-2] [org.zalando.fahrschein.NakadiReader] Starting to listen for events for [b]
2017-05-12 10:31:15,142 {INFO} [pool-11-thread-1] [org.zalando.fahrschein.NakadiReader] Starting to listen for events for [a]
2017-05-12 10:31:15,201 {ERRO} [pool-11-thread-2] [org.app] Unable to listen to event [b]
Caused by: java.lang.NullPointerException
        at org.zalando.fahrschein.ManagedCursorManager.addStreamId(ManagedCursorManager.java:95) ~[fahrschein-0.9.1.jar:?]
        at org.zalando.fahrschein.NakadiReader.openJsonInput(NakadiReader.java:156) ~[fahrschein-0.9.1.jar:?]
        at org.zalando.fahrschein.NakadiReader.runInternal(NakadiReader.java:274) ~[fahrschein-0.9.1.jar:?]
        at org.zalando.fahrschein.NakadiReader.run(NakadiReader.java:262) ~[fahrschein-0.9.1.jar:?]
        at org.zalando.fahrschein.StreamBuilders$AbstractStreamBuilder.listen(StreamBuilders.java:61) ~[fahrschein-0.9.1.jar:?]
        ... 15 more
```

This has already been fixed in https://github.com/zalando-incubator/fahrschein/commit/8ca47e9e385d94e1eefa45462ab1ebd978ae0117 - can we create a new release?

**Comment by jhorstmann** [comment]
Fixed in [release 0.10.0](https://github.com/zalando-incubator/fahrschein/releases/tag/0.10.0)
