### ISSUE TITLE
Give clients the possibility to stop NakadiReader

### ISSUE THREAD

**Issue by tmuehl** [zalando-incubator/fahrschein#67]
As a user of the Fahrschein library, I want to be able to stop the Nakadi consumption manually. E.g.:

```
final Closeable listener = nakadi.client.listen(...);
listener.close();
```

One possibility might be to expose the `JsonInput.close()` or `ClientHttpResponse.close()`.

**Comment by jhorstmann** [comment]
Currently `listen` would block, so you would never reach the `close` line until it already has stopped. I think you can already achieve the same by running the nakadi client in a thread pool or executor service.

I would like to leave any advanced thread pool usage to the user of the library.

**Comment by jhorstmann** [comment]
`NakadiReader` should now handle interruption correctly, so you can run it in a thread pool and `shutdown` the pool or `cancel` the returned `Future`.

**Comment by ievgen-kapinos** [comment]
Hi there!

I also try to stop nakadi gracefully, but there few issues which breaks this idea. Version 0.23.0. Here is my code in Kotlin
```kotlin
    init {
        Runtime.getRuntime().addShutdownHook(
            thread(start = false) {
                // TODO test on single partition event type
                logger.info("Shutdown - interrupting thread $thread")
                thread.interrupt()
                thread.join(Duration.ofSeconds(60).toMillis())
            }
        )
    }
    
    val thread = thread(
        start = false,
        name = "nakadi-listener",
        block = {
            nakadiListener.listen(eventKClass, ::consume). // calls nakadiClient -> stream -> listen
            logger.info("Shutdown - complete")
        }
    )
```

### Issue #1
NakadiReader produces one `INFO` with a stack trace plus `WARN` message. 
This is normal situation. So neither stack traces nor `WARN` level massages should appear. In log it looks like an issue, but it is not.
```
2022-08-29 14:20:22.838 [Thread-3] INFO  d.z.l.c.d.h.b.n.u.u.n.NakadiService2 - Shutdown - interrupting thread Thread[nakadi-listener,5,main]
2022-08-29 14:20:48.268 [nakadi-listener] INFO  org.zalando.fahrschein.NakadiReader - Got [InterruptedIOException] [Interrupted] while reading events for [customer-data-hub.braze-segment-export-start]
java.io.InterruptedIOException: Interrupted
	at org.zalando.fahrschein.NakadiReader.runInternal(NakadiReader.java:287)
	at org.zalando.fahrschein.NakadiReader.run(NakadiReader.java:266)
	at org.zalando.fahrschein.StreamBuilders$AbstractStreamBuilder.listen(StreamBuilders.java:57)
	at de.zalando.lounge.customer.data.hub.shared.nakadi.NakadiListener.listen(NakadiListener.kt:65)
	at de.zalando.lounge.customer.data.hub.shared.nakadi.AbstractNakadiService$thread$1.invoke(AbstractNakadiService.kt:30)
	at de.zalando.lounge.customer.data.hub.shared.nakadi.AbstractNakadiService$thread$1.invoke(AbstractNakadiService.kt:26)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
2022-08-29 14:20:48.270 [nakadi-listener] WARN  org.zalando.fahrschein.NakadiReader - Thread was interrupted
2022-08-29 14:20:48.270 [nakadi-listener] INFO  d.z.l.c.d.h.b.n.u.u.n.NakadiService2 - Shutdown - complete
```
### Issue #2
Relates only to Nakadi events with one partition. If I restart my service with my ShutdownHook, then I have 
```
Exception in thread "nakadi-listener" org.zalando.fahrschein.IOProblem: Problem [about:blank] with status [409]: [Conflict] [No free slots for streaming available. Total slots: 1]
	at org.zalando.fahrschein.ProblemHandlingRequest.handleProblem(ProblemHandlingRequest.java:105)
```
We disconnected gracefully. I assume we should not get `409` error
