### ISSUE TITLE
IllegalArgumentException: Illegal character(s) in message header value:

### ISSUE THREAD

**Issue by qjiang2** [zalando-incubator/fahrschein#76]
Illegal characters in header “X-Nakadi-Cursors” 's value   “[ {\n “partition”:”0”,\n “offset”:”BEGIN”\n}]” 
```java
Caused by: java.lang.IllegalArgumentException: Illegal character(s) in message header value: [ {
  "partition" : "0",
  "offset" : "BEGIN"
} ]
	at sun.net.www.protocol.http.HttpURLConnection.checkMessageHeader(HttpURLConnection.java:508)
	at sun.net.www.protocol.http.HttpURLConnection.isExternalMessageHeaderAllowed(HttpURLConnection.java:459)
	at sun.net.www.protocol.http.HttpURLConnection.addRequestProperty(HttpURLConnection.java:3048)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.addRequestProperty(HttpsURLConnectionImpl.java:331)
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.addHeaders(SimpleBufferingClientHttpRequest.java:104)
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:70)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.zalando.fahrschein.ProblemHandlingClientHttpRequest.execute(ProblemHandlingClientHttpRequest.java:38)
	at org.zalando.fahrschein.NakadiReader.openJsonInput(NakadiReader.java:129)
	at org.zalando.fahrschein.NakadiReader.runInternal(NakadiReader.java:237)
	at org.zalando.fahrschein.NakadiReader.run(NakadiReader.java:224)
	at org.zalando.fahrschein.NakadiClient.listen(NakadiClient.java:110)
	at org.zalando.fahrschein.NakadiClient.listen(NakadiClient.java:101)
	at de.zalando.communication.blacklistservice.nakadiconsumer.NakadiListener.listenEventAndCreateBlacklist(NakadiListener.java:129)
	at de.zalando.communication.blacklistservice.BlacklistServiceApplication.main(BlacklistServiceApplication.java:18)
```

**Comment by jhorstmann** [comment]
The exception happens if jackson is configured with `SerializationFeature.INDENT_OUTPUT`. Serialization of cursors should work independently of the `ObjectMapper` configuration.
