### ISSUE TITLE
Getting exception while trying to enable compression to Nakadi

### ISSUE THREAD

**Issue by mohamedazouz** [zalando-incubator/fahrschein#92]
- I'm trying to enable compression while connecting to nakadi, 
- I'm adding compression as the following 

```
requestFactory = new EnableCompressingRequestFactory(requestFactory); 

class EnableCompressingRequestFactory implements ClientHttpRequestFactory {
    private final ClientHttpRequestFactory delegate;

    public EnableCompressingRequestFactory(final ClientHttpRequestFactory delegate) {
        this.delegate = delegate;
    }

    @Override
    public ClientHttpRequest createRequest(final URI uri, final HttpMethod httpMethod) throws IOException {
        final ClientHttpRequest request = delegate.createRequest(uri, httpMethod);
        request.getHeaders().add("Accept-Encoding", "gzip");
        return request;
    }
}
```
- Unfortunately getting the following errors

```

com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@29daf503; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:484)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2875)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:692)
	at org.zalando.fahrschein.NakadiReader.expectToken(NakadiReader.java:318)
	at org.zalando.fahrschein.NakadiReader.runInternal(NakadiReader.java:247)
	at org.zalando.fahrschein.NakadiReader.run(NakadiReader.java:224)
	at org.zalando.fahrschein.NakadiClient.listen(NakadiClient.java:110)

``` 

**Do you have any idea how can i solve this issue?**

**Comment by jhorstmann** [comment]
Maybe @tmuehl can answer this one, since we are discussing enabling compression in PR #86

**Comment by tmuehl** [comment]
@jhorstmann @mohamedazouz I need to investigate this. Right now, in another application, it's running fine.

**Comment by tmuehl** [comment]
@mohamedazouz It seems to be with your `ClientHttpRequestFactory` (i.e. `SimpleClientHttpRequestFactory`) which doesn't support gzip encoding. Try to use `HttpComponentsClientHttpRequestFactory`.

**Comment by jhorstmann** [comment]
It looks like [`HttpUrlConnection` is not doing the decompression transparently](http://stackoverflow.com/a/20219297/139595), you would have to check the `Content-Encoding` header of the response and wrap it in a `GZIPInputStream` yourself.

**Comment by mohamedazouz** [comment]
@tmuehl it seems like it's working since yesterday, Thanks for your effort

@jhorstmann no need more effort we changed the request factory class and it's working fine to `HttpComponentsClientHttpRequestFactory`
thanks.
